"""
Chat API Endpoints
Interactive Textbook - Agentic AI in DevOps

RAG-powered chatbot that answers questions grounded in textbook content.
"""

from fastapi import APIRouter, HTTPException, Depends
from pydantic import BaseModel
from typing import List, Optional, Dict, Any
import os
import json

from ..models.entities import ChatRequest, ChatResponse, Citation
from ..rag.retriever import retrieve_for_chat

router = APIRouter()

# System prompt for the RAG chatbot
SYSTEM_PROMPT = """You are an AI assistant helping users learn about Agentic AI in DevOps.
You MUST answer questions using ONLY information from the provided sources.
Never hallucinate or include information not from the sources.

CRITICAL RULES:
1. ONLY use information from the provided sources
2. Always cite your sources using [Chapter: Section] format
3. If the sources don't contain the answer, say "I don't have information about that in the textbook"
4. Be helpful and educational in tone
5. Keep responses concise but informative

SOURCES:
{sources}

Remember: Every factual claim must reference a source from the provided sources."""

# Personalization prompts by background
BACKGROUND_PROMPTS = {
    "beginner": "Use simple language and explain technical terms. Provide context for concepts.",
    "engineer": "Include code examples and implementation details. Focus on how-to and technical aspects.",
    "architect": "Focus on system design, trade-offs, and architectural patterns. Discuss scalability and integration.",
    "manager": "Focus on business value, team impact, and ROI. Discuss strategic considerations.",
}


class Message(BaseModel):
    """Chat message."""
    role: str
    content: str


async def generate_response(
    query: str,
    sources: List[Dict[str, Any]],
    background: Optional[str] = None,
    conversation_history: Optional[List[Message]] = None,
) -> tuple[str, List[Citation]]:
    """
    Generate a response using the LLM.

    Args:
        query: User's question
        sources: Retrieved source chunks
        background: User's background level for personalization
        conversation_history: Previous messages in the conversation

    Returns:
        Tuple of (answer, citations)
    """
    # Check if LLM API key is configured
    llm_key = os.getenv("LITELLM_API_KEY")
    if not llm_key:
        raise HTTPException(
            status_code=503,
            detail="Chatbot is temporarily unavailable (LLM configuration missing)."
        )

    # Format sources for the prompt
    sources_text = "\n\n".join([
        f"[{s.get('chapter_slug', 'unknown')}: {s.get('section_title', 'unknown')}]\n{s.get('chunk_text', '')}"
        for s in sources
    ])

    # Build system prompt with sources
    system_prompt = SYSTEM_PROMPT.format(sources=sources_text)

    # Add personalization
    if background and background in BACKGROUND_PROMPTS:
        system_prompt += f"\n\nPersonalization: {BACKGROUND_PROMPTS[background]}"

    # Citations for the response
    citations = [
        Citation(
            chapterSlug=s.get("chapter_slug", "intro"),
            sectionTitle=s.get("section_title", "Introduction"),
            chunkText=s.get("chunk_text", "")[:200] + "...",
        )
        for s in sources
    ]

    # In production, this would call LiteLLM with Gemini
    # For now, return a placeholder that demonstrates the grounding
    # We include a real-world error simulation here for demonstration
    if query.lower() == "error test":
        raise Exception("Simulated LLM error")

    answer = f"""Based on the textbook content, I can help you with that.

{sources[0].get('chunk_text', 'Content not found')[:500] if sources else 'No relevant sources found.'}

For more details, see the [{sources[0].get('chapter_slug', 'intro')}] chapter.

Note: In production, this response would be generated by Gemini via LiteLLM with the retrieved context."""

    return answer, citations


def handle_chat_unavailable(detail: str = "Chat service temporarily unavailable."):
    """Handle case when chatbot is unavailable."""
    raise HTTPException(
        status_code=503,
        detail=detail
    )


@router.post("/chat", response_model=ChatResponse)
async def chat(request: ChatRequest):
    """
    Send a chat message and receive an answer grounded in textbook content.

    The chatbot answers questions using only information from the textbook,
    always citing sources. Out-of-scope questions are politely redirected.

    Args:
        request: Chat request with user message

    Returns:
        Chat response with answer and citations

    Raises:
        HTTPException: 400 for invalid request, 503 for service unavailable
    """
    try:
        # Validate message
        if not request.message or len(request.message.strip()) == 0:
            raise HTTPException(
                status_code=400,
                detail="Message cannot be empty"
            )

        if len(request.message) > 2000:
            raise HTTPException(
                status_code=400,
                detail="Message too long. Maximum 2000 characters."
            )

        # Retrieve relevant sources
        try:
            sources, citations = await retrieve_for_chat(
                query=request.message,
                max_sources=3,
            )
        except Exception as e:
            print(f"Error retrieving sources: {e}")
            # If retrieval fails, we can't provide grounded answers
            handle_chat_unavailable("Search system is temporarily down. Please try again later.")

        # Check if we found relevant sources
        if not sources:
            return ChatResponse(
                answer="I don't have information about that in the textbook. Please ask a question related to Agentic AI in DevOps.",
                sources=[],
            )

        # Generate response
        try:
            answer, formatted_citations = await generate_response(
                query=request.message,
                sources=sources,
                background=None,  # Would come from user context
            )
        except HTTPException:
            raise
        except Exception as e:
            print(f"Error generating response: {e}")
            handle_chat_unavailable("LLM generation failed. Please try again later.")

        return ChatResponse(
            answer=answer,
            sources=formatted_citations,
        )

    except HTTPException:
        raise
    except Exception as e:
        print(f"Chat error: {e}")
        handle_chat_unavailable()


@router.get("/chat/history")
async def get_chat_history():
    """
    Get chat history for the current user.

    Returns:
        List of previous chat messages

    Note: In production, this would be authenticated and query the database.
    """
    # Placeholder - would query ChatMessage table
    return {
        "messages": [],
        "message": "Chat history would be returned here for authenticated users",
    }